// <auto-generated />
using AtividadeAspNet1.db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AtividadeAspNet1.Migrations
{
    [DbContext(typeof(Conexao))]
    [Migration("20250502190057_WiiDante")]
    partial class WiiDante
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AtividadeAspNet1.Models.Maquina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_maquina");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FkUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("fk_usuario");

                    b.Property<int>("HardDisk")
                        .HasColumnType("integer")
                        .HasColumnName("harddisk");

                    b.Property<int>("MemoriaRam")
                        .HasColumnType("integer")
                        .HasColumnName("memoria_ram");

                    b.Property<int>("PlacaRede")
                        .HasColumnType("integer")
                        .HasColumnName("placa_rede");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<int>("velocidade")
                        .HasColumnType("integer")
                        .HasColumnName("velocidade");

                    b.HasKey("Id");

                    b.HasIndex("FkUsuario");

                    b.ToTable("maquina");
                });

            modelBuilder.Entity("AtividadeAspNet1.Models.Software", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_software");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Harddisk")
                        .HasColumnType("integer")
                        .HasColumnName("harddisk");

                    b.Property<string>("Produto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("produto");

                    b.Property<int>("Ram")
                        .HasColumnType("integer")
                        .HasColumnName("memoria_ram");

                    b.Property<int>("fk_maquina")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("fk_maquina");

                    b.ToTable("software");
                });

            modelBuilder.Entity("AtividadeAspNet1.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("especialidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("especialidade");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_usuario");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int>("ramal")
                        .HasColumnType("integer")
                        .HasColumnName("ramal");

                    b.HasKey("Id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("AtividadeAspNet1.Models.Maquina", b =>
                {
                    b.HasOne("AtividadeAspNet1.Models.Usuarios", "Usuarios")
                        .WithMany()
                        .HasForeignKey("FkUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AtividadeAspNet1.Models.Software", b =>
                {
                    b.HasOne("AtividadeAspNet1.Models.Maquina", "maquina")
                        .WithMany()
                        .HasForeignKey("fk_maquina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("maquina");
                });
#pragma warning restore 612, 618
        }
    }
}
